# Generated by Django 5.0.2 on 2024-11-22 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_likes_hashtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='posts',
        ),
    ]
